### ISSUE TITLE
Unclear code

### ISSUE THREAD

**Issue by Sanduhr32** [duncte123/botCommons#5]
- [ ] Also missing docs.
- [ ] `EmbedUtils#setDefaultColor(Color / int)` & overloading `EmbedUtils#getColorOrDefault(long guildId)` that falls back to the set color for avoiding repeated arguments. Also could use a Supplier/Function to get a color
- [ ] Renaming variables like `long key` to `long guildId` for having more descriptive parameter names.
- [ ] `MessageUtils#sendMsg()` (yes the main one where everything gets piped through) The MessageBuilder contains `dunctebot` in its nonce, which seems inappropriate for other bots.

**Comment by duncte123** [comment]
> StringUtils#capitalizeFully(String string) only capitalizes the first letter of each word. With fully in it's name, i'ld assume that it capitalizes the whole string.

_"Capitalization (North American English) or capitalisation (British English) is writing a word with its first letter as a capital letter (uppercase letter) and the remaining letters in lower case, in writing systems with a case distinction. The term also may refer to the choice of the casing applied to text."_

**Comment by Sanduhr32** [comment]
Fully is an adjective describing a term more accurate.
