### ISSUE TITLE
Version 33c00a5 dont work?

### ISSUE THREAD

**Issue by derDennis99** [duncte123/botCommons#6]
Hello,

I have the following problem:
I have changed the version from "fbb8f98" to "33c00a5" I always get an error in the code where the EmbedBuilder and MessageEmbed are used ... how can I solve the problem? what am I doing wrong?

Thank you

![Unbenannt](https://user-images.githubusercontent.com/59368378/99148016-abd06800-2685-11eb-85c2-65b69254c6e9.JPG)

**Comment by duncte123** [comment]
With your current provided info I cannot diagnose your issue, also please note that only official bintray releases are supported, I cannot guarantee that git commits are working

**Comment by derDennis99** [comment]
This is the Gradle:
`plugins {
    id'java'
    id'application'
    id'com.github.johnrengelman.shadow' version '2.0.4'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'me.duncte123.ge.Main'
        )
    }
}

mainClassName = 'me.duncte123.ge.Main'

version '1.0'

sourceCompatibility = '14'

repositories {
    jcenter()
    mavenCentral()

    maven {
        url 'https://jitpack.io'
    }
}

dependencies {

    compile group: 'net.dv8tion', name: 'JDA', version: '3.8.0_434'
    compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'
    compile group: 'org.json', name: 'json', version: '20180130'
    compile group: 'com.afollestad', name:'ason', version:'1.4.14'
    //implementation group: 'com.github.duncte123', name: 'botCommons', version: 'fbb8f98'
    implementation group: 'com.github.duncte123', name: 'botCommons', version: '33c00a5'
    implementation group: 'net.sourceforge.htmlunit', name: 'htmlunit', version: '2.13'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.6'
}

compileJava.options.encoding = 'UTF-8'`


JDK Version: 14
what can I give you for info?

**Comment by duncte123** [comment]
update JDA, I'm surprised your bot would still come online with JDA 3

**Comment by derDennis99** [comment]
ok i updated the version to the latest: 4.2.0_215
now i get this: `Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`

**Comment by duncte123** [comment]
That is unrelated to botCommons

**Comment by derDennis99** [comment]
now i get:
`java: cannot find symbol
  symbol:   method defaultEmbed()
  location: class me.duncte123.botcommons.messaging.EmbedUtils`

**Comment by duncte123** [comment]
That is because you bumped from version 1 to version 2 (a rewrite) check the usage linked in the readme

**Comment by derDennis99** [comment]
"update JDA, I'm surprised your bot would still come online with JDA 3"

that was it sooorryyyy...

it had nothing to do with your project ... I had to update my complete program code to the new JDA ... now it's running like a freshly lubricated clockwork again. Thank you!
