### ISSUE TITLE
JDA5 Support

### ISSUE THREAD

**Issue by silverfox0000** [duncte123/botCommons#7]
Will there be support for [JDA5](https://github.com/DV8FromTheWorld/JDA/releases/tag/v5.0.0-alpha.2) in the next release?

**Comment by duncte123** [comment]
I'm planning on adding JDA 5 support once it's released

**Comment by duncte123** [comment]
In the meantime, here's a beta that should suffice until JDA 5 does release
```kts
maven {
    url = uri("https://m2.duncte123.dev/snapshots")
}

dependencies {
    implementation("me.duncte123:botCommons:beta_3.0.3")
}
```

**Comment by duncte123** [comment]
Released version beta_3.0.5 that works with beta 2 of jda 5

**Comment by duncte123** [comment]
Closing this as v3.0.16 has been released with JDA 5 support
